name: adb_wifi_connector_server
description: A socket server used to connect an Android phone to ADB via Wifi
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.14.1 <3.0.0"

dependencies:
  adb_wifi_connector_commons:
    path: ../commons

dev_dependencies:
  code_coverage: ^1.2.0
  lints: ^1.0.0
  mocktail: ^0.1.4
  test: ^1.18.2
